workflows:
  ios-release:
    name: Smashrite Core – iOS (Auto-sign + TestFlight)
    max_build_duration: 60

    environment:
      flutter: 3.29.3
      xcode: 16.3
      cocoapods: default
      groups:
        - smashrite-vars

      vars:
        BUNDLE_ID: com.smashrite.core.ios
        APPLE_TEAM_ID: "6N74MV2D96"

      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID

    scripts:
      - name: Set iOS bundle identifier dynamically
        script: |
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" ios/Runner/Info.plist

          sed -i '' "s/PRODUCT_BUNDLE_IDENTIFIER = .*/PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID;/g" ios/Runner.xcodeproj/project.pbxproj

      - name: Install dependencies
        script: flutter pub get

      - name: Build IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true